### ISSUE TITLE
Allow usage of POSTGRESQL_CONNECTION_URI instead of separate db/password/user in helm chart

### ISSUE THREAD

**Issue by SkeLLLa** [supertokens/supertokens-docker-postgresql#28]
Allowing usage of `POSTGRESQL_CONNECTION_URI` which simplify setups and sometimes it works much better, since through connection URI various other parameters could be configured, while currently through standard db/pass/user is not possible.

**Comment by rishabhpoddar** [comment]
Hey @SkeLLLa we already have this config. See [here](https://github.com/supertokens/supertokens-postgresql-plugin/blob/master/config.yaml#L9).

Closing this issue for now, but feel free to reopen.

**Comment by SkeLLLa** [comment]
@rishabhpoddar there's no such option in helm [config](https://github.com/supertokens/supertokens-docker-postgresql/blob/master/helm-chart/values.yaml#L15).

The link you've provided leading to completely different product - supertokens-postgresql-plugin and I'm talking about helm chart.

**Comment by rishabhpoddar** [comment]
Right. So the helm chart is a community contributed chart. The docker image itself (supertokens-docker-postgresql) is built using the repo link i had shared, so the docker env var does accept this config.

Please feel free to create a PR for the helm chart to add this env var.

**Comment by SkeLLLa** [comment]
@rishabhpoddar done.
